---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htmlapp-deployment
  labels:
    app: htmlapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmlapp
  template:
    metadata:
      labels:
        app: htmlapp
    spec:
      containers:
      - name: htmlapp
        image: azesu.azurecr.io/web-app-html:v1
        ports:
        - containerPort: 80
          name: htmlapp
