---
apiVersion: v1
kind: Service
metadata:
  name: htmlapp-service
  labels:
    app: htmlapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: htmlapp-port
  selector:
    app: htmlapp
